<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::disableQueryLog();

        $items = array(
            array('id' => '1', 'name' => ['en' => 'Yemen', 'ar' => 'اليمن'], 'code' => 'YE'  ),
            array('id' => '2', 'name' => ['en' => 'Canada', 'ar' => 'كندا'], 'code' => 'CA'),
            array('id' => '3', 'name' => ['en' => 'Japan', 'ar' => 'اليابان'], 'code' => 'JP'),
            array('id' => '4', 'name' => ['en' => 'Algeria', 'ar' => 'الجزائر'], 'code' => 'DZ'),
            array('id' => '5', 'name' => ['en' => 'South Africa', 'ar' => 'جنوب أفريقيا'], 'code' => 'ZA'),
            array('id' => '6', 'name' => ['en' => 'Chile', 'ar' => 'تشيلي'], 'code' => 'CL'),
            array('id' => '7', 'name' => ['en' => 'Singapore', 'ar' => 'سنغافورة'], 'code' => 'SG'),
            array('id' => '8', 'name' => ['en' => 'Norway', 'ar' => 'النرويج'], 'code' => 'NO'),
            array('id' => '9', 'name' => ['en' => 'Uzbekistan', 'ar' => 'أوزبكستان'], 'code' => 'UZ'),
            array('id' => '10', 'name' => ['en' => 'Hungary', 'ar' => 'المجر'], 'code' => 'HU'),
            array('id' => '11', 'name' => ['en' => 'Republic of Ireland', 'ar' => 'جمهورية أيرلندا'], 'code' => 'IE'),
            array('id' => '12', 'name' => ['en' => 'Bahrain', 'ar' => 'البحرين'], 'code' => 'BH'),
            array('id' => '13', 'name' => ['en' => 'Liechtenstein', 'ar' => 'ليختنشتاين'], 'code' => 'LI'),
            array('id' => '14', 'name' => ['en' => 'Armenia', 'ar' => 'أرمينيا'], 'code' => 'AM'),
            array('id' => '15', 'name' => ['en' => 'Serbia', 'ar' => 'صربيا'], 'code' => 'RS'),
            array('id' => '16', 'name' => ['en' => 'Spain', 'ar' => 'إسبانيا'], 'code' => 'ES'),
            array('id' => '17', 'name' => ['en' => 'United States of America', 'ar' => 'الولايات المتحدة'], 'code' => 'US'),
            array('id' => '18', 'name' => ['en' => 'Argentina', 'ar' => 'الأرجنتين'], 'code' => 'AR'),
            array('id' => '19', 'name' => ['en' => 'Cambodia', 'ar' => 'كمبوديا'], 'code' => 'KH'),
            array('id' => '20', 'name' => ['en' => 'Belgium', 'ar' => 'بلجيكا'], 'code' => 'BE'),
            array('id' => '21', 'name' => ['en' => 'Finland', 'ar' => 'فنلندا'], 'code' => 'FI'),
            array('id' => '22', 'name' => ['en' => 'Australia', 'ar' => 'أستراليا'], 'code' => 'AU'),
            array('id' => '23', 'name' => ['en' => 'North Korea', 'ar' => 'كوريا الشمالية'], 'code' => 'KP'),
            array('id' => '24', 'name' => ['en' => 'Peru', 'ar' => 'بيرو'], 'code' => 'PE'),
            array('id' => '25', 'name' => ['en' => 'India', 'ar' => 'الهند'], 'code' => 'IN'),
            array('id' => '26', 'name' => ['en' => 'Solomon Islands', 'ar' => 'جزر سليمان'], 'code' => 'SB'),
            array('id' => '27', 'name' => ['en' => 'Italy', 'ar' => 'إيطاليا'], 'code' => 'IT'),
            array('id' => '28', 'name' => ['en' => 'Chad', 'ar' => 'تشاد'], 'code' => 'TD'),
            array('id' => '29', 'name' => ['en' => 'East Timor', 'ar' => 'تيمور الشرقية'], 'code' => 'TL'),
            array('id' => '30', 'name' => ['en' => 'Sweden', 'ar' => 'السويد'], 'code' => 'SE'),
            array('id' => '31', 'name' => ['en' => 'Poland', 'ar' => 'بولندا'], 'code' => 'PL'),
            array('id' => '32', 'name' => ['en' => 'Luxembourg', 'ar' => 'لوكسمبورغ'], 'code' => 'LU'),
            array('id' => '33', 'name' => ['en' => 'Tonga', 'ar' => 'تونغا'], 'code' => 'TO'),
            array('id' => '34', 'name' => ['en' => 'Samoa', 'ar' => 'ساموا'], 'code' => 'WS'),
            array('id' => '35', 'name' => ['en' => 'Tuvalu', 'ar' => 'توفالو'], 'code' => 'TV'),
            array('id' => '36', 'name' => ['en' => 'Vanuatu', 'ar' => 'فانواتو'], 'code' => 'VU'),
            array('id' => '37', 'name' => ['en' => 'New Zealand', 'ar' => 'نيوزيلندا'], 'code' => 'NZ'),
            array('id' => '38', 'name' => ['en' => 'Lithuania', 'ar' => 'ليتوانيا'], 'code' => 'LT'),
            array('id' => '39', 'name' => ['en' => 'Palau', 'ar' => 'بالاو'], 'code' => 'PW'),
            array('id' => '40', 'name' => ['en' => 'Papua New Guinea', 'ar' => 'بابوا غينيا الجديدة'], 'code' => 'PG'),
            array('id' => '41', 'name' => ['en' => 'Austria', 'ar' => 'النمسا'], 'code' => 'AT'),
            array('id' => '42', 'name' => ['en' => 'Greece', 'ar' => 'اليونان'], 'code' => 'GR'),
            array('id' => '43', 'name' => ['en' => 'Switzerland', 'ar' => 'سويسرا'], 'code' => 'CH'),
            array('id' => '44', 'name' => ['en' => 'Nauru', 'ar' => 'ناورو'], 'code' => 'NR'),
            array('id' => '45', 'name' => ['en' => 'Turkey', 'ar' => 'تركيا'], 'code' => 'TR'),
            array('id' => '46', 'name' => ['en' => 'Marshall Islands', 'ar' => 'جزر مارشال'], 'code' => 'MH'),
            array('id' => '47', 'name' => ['en' => 'Federated States of Micronesia', 'ar' => 'ولايات ميكرونيسيا المتحدة'], 'code' => 'FM'),
            array('id' => '48', 'name' => ['en' => 'Portugal', 'ar' => 'البرتغال'], 'code' => 'PT'),
            array('id' => '49', 'name' => ['en' => 'Uruguay', 'ar' => 'الأوروغواي'], 'code' => 'UY'),
            array('id' => '50', 'name' => ['en' => 'Kiribati', 'ar' => 'كيريباتي'], 'code' => 'KI'),
            array('id' => '51', 'name' => ['en' => 'Mongolia', 'ar' => 'منغوليا'], 'code' => 'MN'),
            array('id' => '52', 'name' => ['en' => 'Egypt', 'ar' => 'مصر'], 'code' => 'EG'),
            array('id' => '53', 'name' => ['en' => 'Fiji', 'ar' => 'فيجي'], 'code' => 'FJ'),
            array('id' => '54', 'name' => ['en' => 'Mexico', 'ar' => 'المكسيك'], 'code' => 'MX'),
            array('id' => '55', 'name' => ['en' => 'Suriname', 'ar' => 'سورينام'], 'code' => 'SR'),
            array('id' => '56', 'name' => ['en' => 'Venezuela', 'ar' => 'فنزويلا'], 'code' => 'VE'),
            array('id' => '57', 'name' => ['en' => 'Guyana', 'ar' => 'غيانا'], 'code' => 'GY'),
            array('id' => '58', 'name' => ['en' => 'Kenya', 'ar' => 'كينيا'], 'code' => 'KE'),
            array('id' => '59', 'name' => ['en' => 'Ethiopia', 'ar' => 'إثيوبيا'], 'code' => 'ET'),
            array('id' => '60', 'name' => ['en' => 'Ecuador', 'ar' => 'الإكوادور'], 'code' => 'EC'),
            array('id' => '61', 'name' => ['en' => 'People\'s Republic of China', 'ar' => 'الصين'], 'code' => 'CN'),
            array('id' => '62', 'name' => ['en' => 'France', 'ar' => 'فرنسا'], 'code' => 'FR'),
            array('id' => '63', 'name' => ['en' => 'Ghana', 'ar' => 'غانا'], 'code' => 'GH'),
            array('id' => '64', 'name' => ['en' => 'United Kingdom', 'ar' => 'المملكة المتحدة'], 'code' => 'GB'),
            array('id' => '65', 'name' => ['en' => 'Paraguay', 'ar' => 'باراغواي'], 'code' => 'PY'),
            array('id' => '66', 'name' => ['en' => 'Colombia', 'ar' => 'كولومبيا'], 'code' => 'CO'),
            array('id' => '67', 'name' => ['en' => 'Bolivia', 'ar' => 'بوليفيا'], 'code' => 'BO'),
            array('id' => '68', 'name' => ['en' => 'Trinidad and Tobago', 'ar' => 'ترينيداد وتوباغو'], 'code' => 'TT'),
            array('id' => '69', 'name' => ['en' => 'Brazil', 'ar' => 'البرازيل'], 'code' => 'BR'),
            array('id' => '70', 'name' => ['en' => 'Saint Vincent and the Grenadines', 'ar' => 'سانت فينسنت والغرينادين'], 'code' => 'VC'),
            array('id' => '71', 'name' => ['en' => 'Russia', 'ar' => 'روسيا'], 'code' => 'RU'),
            array('id' => '72', 'name' => ['en' => 'Saint Lucia', 'ar' => 'سانت لوسيا'], 'code' => 'LC'),
            array('id' => '73', 'name' => ['en' => 'Germany', 'ar' => 'ألمانيا'], 'code' => 'DE'),
            array('id' => '74', 'name' => ['en' => 'Saint Kitts and Nevis', 'ar' => 'سانت كيتس ونيفيس'], 'code' => 'KN'),
            array('id' => '75', 'name' => ['en' => 'Belarus', 'ar' => 'بيلاروس'], 'code' => 'BY'),
            array('id' => '76', 'name' => ['en' => 'Iceland', 'ar' => 'آيسلندا'], 'code' => 'IS'),
            array('id' => '77', 'name' => ['en' => 'Guatemala', 'ar' => 'غواتيمالا'], 'code' => 'GT'),
            array('id' => '78', 'name' => ['en' => 'Antigua and Barbuda', 'ar' => 'أنتيغوا وباربودا'], 'code' => 'AG'),
            array('id' => '79', 'name' => ['en' => 'Grenada', 'ar' => 'غرينادا'], 'code' => 'GD'),
            array('id' => '80', 'name' => ['en' => 'Jamaica', 'ar' => 'جامايكا'], 'code' => 'JM'),
            array('id' => '81', 'name' => ['en' => 'Honduras', 'ar' => 'هندوراس'], 'code' => 'HN'),
            array('id' => '82', 'name' => ['en' => 'Estonia', 'ar' => 'إستونيا'], 'code' => 'EE'),
            array('id' => '83', 'name' => ['en' => 'Latvia', 'ar' => 'لاتفيا'], 'code' => 'LV'),
            array('id' => '84', 'name' => ['en' => 'Czech Republic', 'ar' => 'التشيك'], 'code' => 'CZ'),
            array('id' => '85', 'name' => ['en' => 'Dominican Republic', 'ar' => 'جمهورية الدومينيكان'], 'code' => 'DO'),
            array('id' => '86', 'name' => ['en' => 'The Bahamas', 'ar' => 'باهاماس'], 'code' => 'BS'),
            array('id' => '87', 'name' => ['en' => 'Haiti', 'ar' => 'هايتي'], 'code' => 'HT'),
            array('id' => '88', 'name' => ['en' => 'Dominica', 'ar' => 'دومينيكا'], 'code' => 'DM'),
            array('id' => '89', 'name' => ['en' => 'Ukraine', 'ar' => 'أوكرانيا'], 'code' => 'UA'),
            array('id' => '90', 'name' => ['en' => 'Slovakia', 'ar' => 'سلوفاكيا'], 'code' => 'SK'),
            array('id' => '91', 'name' => ['en' => 'Moldova', 'ar' => 'مولدوفا'], 'code' => 'MD'),
            array('id' => '92', 'name' => ['en' => 'Iraq', 'ar' => 'العراق'], 'code' => 'IQ'),
            array('id' => '93', 'name' => ['en' => 'El Salvador', 'ar' => 'السلفادور'], 'code' => 'SV'),
            array('id' => '94', 'name' => ['en' => 'Costa Rica', 'ar' => 'كوستاريكا'], 'code' => 'CR'),
            array('id' => '95', 'name' => ['en' => 'Iran', 'ar' => 'إيران'], 'code' => 'IR'),
            array('id' => '96', 'name' => ['en' => 'Israel', 'ar' => 'إسرائيل'], 'code' => 'IL'),
            array('id' => '97', 'name' => ['en' => 'Slovenia', 'ar' => 'سلوفينيا'], 'code' => 'SI'),
            array('id' => '98', 'name' => ['en' => 'Panama', 'ar' => 'بنما'], 'code' => 'PA'),
            array('id' => '99', 'name' => ['en' => 'Romania', 'ar' => 'رومانيا'], 'code' => 'RO'),
            array('id' => '100', 'name' => ['en' => 'Bulgaria', 'ar' => 'بلغاريا'], 'code' => 'BG'),
            array('id' => '101', 'name' => ['en' => 'Jordan', 'ar' => 'الأردن'], 'code' => 'JO'),
            array('id' => '102', 'name' => ['en' => 'North Macedonia', 'ar' => 'مقدونيا الشمالية'], 'code' => 'MK'),
            array('id' => '103', 'name' => ['en' => 'Albania', 'ar' => 'ألبانيا'], 'code' => 'AL'),
            array('id' => '104', 'name' => ['en' => 'Croatia', 'ar' => 'كرواتيا'], 'code' => 'HR'),
            array('id' => '105', 'name' => ['en' => 'Kyrgyzstan', 'ar' => 'قيرغيزستان'], 'code' => 'KG'),
            array('id' => '106', 'name' => ['en' => 'Nicaragua', 'ar' => 'نيكاراغوا'], 'code' => 'NI'),
            array('id' => '107', 'name' => ['en' => 'Bosnia and Herzegovina', 'ar' => 'البوسنة والهرسك'], 'code' => 'BA'),
            array('id' => '108', 'name' => ['en' => 'Laos', 'ar' => 'لاوس'], 'code' => 'LA'),
            array('id' => '109', 'name' => ['en' => 'Azerbaijan', 'ar' => 'أذربيجان'], 'code' => 'AZ'),
            array('id' => '110', 'name' => ['en' => 'Kuwait', 'ar' => 'الكويت'], 'code' => 'KW'),
            array('id' => '111', 'name' => ['en' => 'Maldives', 'ar' => 'المالديف'], 'code' => 'MV'),
            array('id' => '112', 'name' => ['en' => 'Lebanon', 'ar' => 'لبنان'], 'code' => 'LB'),
            array('id' => '113', 'name' => ['en' => 'Malaysia', 'ar' => 'ماليزيا'], 'code' => 'MY'),
            array('id' => '114', 'name' => ['en' => 'Myanmar', 'ar' => 'ميانمار'], 'code' => 'MM'),
            array('id' => '115', 'name' => ['en' => 'Andorra', 'ar' => 'أندورا'], 'code' => 'AD'),
            array('id' => '116', 'name' => ['en' => 'Cyprus', 'ar' => 'قبرص'], 'code' => 'CY'),
            array('id' => '117', 'name' => ['en' => 'Kazakhstan', 'ar' => 'كازاخستان'], 'code' => 'KZ'),
            array('id' => '118', 'name' => ['en' => 'Georgia', 'ar' => 'جورجيا'], 'code' => 'GE'),
            array('id' => '119', 'name' => ['en' => 'Oman', 'ar' => 'سلطنة عمان'], 'code' => 'OM'),
            array('id' => '120', 'name' => ['en' => 'Nepal', 'ar' => 'نيبال'], 'code' => 'NP'),
            array('id' => '121', 'name' => ['en' => 'Malta', 'ar' => 'مالطا'], 'code' => 'MT'),
            array('id' => '122', 'name' => ['en' => 'Monaco', 'ar' => 'موناكو'], 'code' => 'MC'),
            array('id' => '123', 'name' => ['en' => 'Pakistan', 'ar' => 'باكستان'], 'code' => 'PK'),
            array('id' => '124', 'name' => ['en' => 'Vatican City', 'ar' => 'الفاتيكان'], 'code' => 'VA'),
            array('id' => '125', 'name' => ['en' => 'Qatar', 'ar' => 'قطر'], 'code' => 'QA'),
            array('id' => '126', 'name' => ['en' => 'Montenegro', 'ar' => 'الجبل الأسود'], 'code' => 'ME'),
            array('id' => '127', 'name' => ['en' => 'Saudi Arabia', 'ar' => 'السعودية'], 'code' => 'SA'),
            array('id' => '128', 'name' => ['en' => 'Belize', 'ar' => 'بليز'], 'code' => 'BZ'),
            array('id' => '129', 'name' => ['en' => 'Cuba', 'ar' => 'كوبا'], 'code' => 'CU'),
            array('id' => '130', 'name' => ['en' => 'Indonesia', 'ar' => 'إندونيسيا'], 'code' => 'ID'),
            array('id' => '131', 'name' => ['en' => 'Syria', 'ar' => 'سوريا'], 'code' => 'SY'),
            array('id' => '132', 'name' => ['en' => 'Taiwan', 'ar' => 'تايوان'], 'code' => 'TW'),
            array('id' => '133', 'name' => ['en' => 'Sri Lanka', 'ar' => 'سريلانكا'], 'code' => 'LK'),
            array('id' => '134', 'name' => ['en' => 'Comoros', 'ar' => 'جزر القمر'], 'code' => 'KM'),
            array('id' => '135', 'name' => ['en' => 'Tajikistan', 'ar' => 'طاجيكستان'], 'code' => 'TJ'),
            array('id' => '136', 'name' => ['en' => 'Republic of the Congo', 'ar' => 'جمهورية الكونغو'], 'code' => 'CG'),
            array('id' => '137', 'name' => ['en' => 'South Korea', 'ar' => 'كوريا الجنوبية'], 'code' => 'KR'),
            array('id' => '138', 'name' => ['en' => 'United Arab Emirates', 'ar' => 'الإمارات العربية المتحدة'], 'code' => 'AE'),
            array('id' => '139', 'name' => ['en' => 'San Marino', 'ar' => 'سان مارينو'], 'code' => 'SM'),
            array('id' => '140', 'name' => ['en' => 'Turkmenistan', 'ar' => 'تركمانستان'], 'code' => 'TM'),
            array('id' => '141', 'name' => ['en' => 'Equatorial Guinea', 'ar' => 'غينيا الاستوائية'], 'code' => 'GQ'),
            array('id' => '142', 'name' => ['en' => 'Democratic Republic of the Congo', 'ar' => 'جمهورية الكونغو الديمقراطية'], 'code' => 'CD'),
            array('id' => '143', 'name' => ['en' => 'Barbados', 'ar' => 'باربادوس'], 'code' => 'BB'),
            array('id' => '144', 'name' => ['en' => 'Angola', 'ar' => 'أنغولا'], 'code' => 'AO'),
            array('id' => '145', 'name' => ['en' => 'Gabon', 'ar' => 'الغابون'], 'code' => 'GA'),
            array('id' => '146', 'name' => ['en' => 'Guinea', 'ar' => 'غينيا'], 'code' => 'GN'),
            array('id' => '147', 'name' => ['en' => 'Guinea-Bissau', 'ar' => 'غينيا بيساو'], 'code' => 'GW'),
            array('id' => '148', 'name' => ['en' => 'Tanzania', 'ar' => 'تنزانيا'], 'code' => 'TZ'),
            array('id' => '149', 'name' => ['en' => 'Mali', 'ar' => 'مالي'], 'code' => 'ML'),
            array('id' => '150', 'name' => ['en' => 'Bhutan', 'ar' => 'بوتان'], 'code' => 'BT'),
            array('id' => '151', 'name' => ['en' => 'Djibouti', 'ar' => 'جيبوتي'], 'code' => 'DJ'),
            array('id' => '152', 'name' => ['en' => 'Vietnam', 'ar' => 'فيتنام'], 'code' => 'VN'),
            array('id' => '153', 'name' => ['en' => 'Thailand', 'ar' => 'تايلاند'], 'code' => 'TH'),
            array('id' => '154', 'name' => ['en' => 'Eritrea', 'ar' => 'إريتريا'], 'code' => 'ER'),
            array('id' => '155', 'name' => ['en' => 'The Gambia', 'ar' => 'غامبيا'], 'code' => 'GM'),
            array('id' => '156', 'name' => ['en' => 'Ivory Coast', 'ar' => 'ساحل العاج'], 'code' => 'CI'),
            array('id' => '157', 'name' => ['en' => 'Philippines', 'ar' => 'الفلبين'], 'code' => 'PH'),
            array('id' => '158', 'name' => ['en' => 'Afghanistan', 'ar' => 'أفغانستان'], 'code' => 'AF'),
            array('id' => '159', 'name' => ['en' => 'Central African Republic', 'ar' => 'جمهورية أفريقيا الوسطى'], 'code' => 'CF'),
            array('id' => '160', 'name' => ['en' => 'Bangladesh', 'ar' => 'بنغلاديش'], 'code' => 'BD'),
            array('id' => '161', 'name' => ['en' => 'Zimbabwe', 'ar' => 'زيمبابوي'], 'code' => 'ZW'),
            array('id' => '162', 'name' => ['en' => 'Togo', 'ar' => 'توغو'], 'code' => 'TG'),
            array('id' => '163', 'name' => ['en' => 'Cameroon', 'ar' => 'الكاميرون'], 'code' => 'CM'),
            array('id' => '164', 'name' => ['en' => 'Brunei', 'ar' => 'بروناي'], 'code' => 'BN'),
            array('id' => '165', 'name' => ['en' => 'Liberia', 'ar' => 'ليبيريا'], 'code' => 'LR'),
            array('id' => '166', 'name' => ['en' => 'Tunisia', 'ar' => 'تونس'], 'code' => 'TN'),
            array('id' => '167', 'name' => ['en' => 'Malawi', 'ar' => 'مالاوي'], 'code' => 'MW'),
            array('id' => '168', 'name' => ['en' => 'Lesotho', 'ar' => 'ليسوتو'], 'code' => 'LS'),
            array('id' => '169', 'name' => ['en' => 'Libya', 'ar' => 'ليبيا'], 'code' => 'LY'),
            array('id' => '170', 'name' => ['en' => 'South Sudan', 'ar' => 'جنوب السودان'], 'code' => 'SS'),
            array('id' => '171', 'name' => ['en' => 'Benin', 'ar' => 'بنين'], 'code' => 'BJ'),
            array('id' => '172', 'name' => ['en' => 'Cape Verde', 'ar' => 'الرأس الأخضر'], 'code' => 'CV'),
            array('id' => '173', 'name' => ['en' => 'Mauritius', 'ar' => 'موريشيوس'], 'code' => 'MU'),
            array('id' => '174', 'name' => ['en' => 'Zambia', 'ar' => 'زامبيا'], 'code' => 'ZM'),
            array('id' => '175', 'name' => ['en' => 'Burkina Faso', 'ar' => 'بوركينا فاسو'], 'code' => 'BF'),
            array('id' => '176', 'name' => ['en' => 'Botswana', 'ar' => 'بوتسوانا'], 'code' => 'BW'),
            array('id' => '177', 'name' => ['en' => 'Madagascar', 'ar' => 'مدغشقر'], 'code' => 'MG'),
            array('id' => '178', 'name' => ['en' => 'State of Palestine', 'ar' => 'دولة فلسطين'], 'code' => 'PS'),
            array('id' => '179', 'name' => ['en' => 'Mauritania', 'ar' => 'موريتانيا'], 'code' => 'MR'),
            array('id' => '180', 'name' => ['en' => 'Burundi', 'ar' => 'بوروندي'], 'code' => 'BI'),
            array('id' => '181', 'name' => ['en' => 'Mozambique', 'ar' => 'موزمبيق'], 'code' => 'MZ'),
            array('id' => '182', 'name' => ['en' => 'Namibia', 'ar' => 'ناميبيا'], 'code' => 'NA'),
            array('id' => '183', 'name' => ['en' => 'Nigeria', 'ar' => 'نيجيريا'], 'code' => 'NG'),
            array('id' => '184', 'name' => ['en' => 'Niger', 'ar' => 'النيجر'], 'code' => 'NE'),
            array('id' => '185', 'name' => ['en' => 'Rwanda', 'ar' => 'رواندا'], 'code' => 'RW'),
            array('id' => '186', 'name' => ['en' => 'Senegal', 'ar' => 'السنغال'], 'code' => 'SN'),
            array('id' => '187', 'name' => ['en' => 'São Tomé and Príncipe', 'ar' => 'ساو تومي وبرينسيب'], 'code' => 'ST'),
            array('id' => '188', 'name' => ['en' => 'Morocco', 'ar' => 'المغرب'], 'code' => 'MA'),
            array('id' => '189', 'name' => ['en' => 'Uganda', 'ar' => 'أوغندا'], 'code' => 'UG'),
            array('id' => '190', 'name' => ['en' => 'Sierra Leone', 'ar' => 'سيراليون'], 'code' => 'SL'),
            array('id' => '191', 'name' => ['en' => 'Seychelles', 'ar' => 'سيشل'], 'code' => 'SC'),
            array('id' => '192', 'name' => ['en' => 'Somalia', 'ar' => 'الصومال'], 'code' => 'SO'),
            array('id' => '193', 'name' => ['en' => 'Eswatini', 'ar' => 'إسواتيني'], 'code' => 'SZ'),
            array('id' => '194', 'name' => ['en' => 'Sudan', 'ar' => 'السودان'], 'code' => 'SD'),
            array('id' => '195', 'name' => ['en' => 'Kingdom of the Netherlands', 'ar' => 'مملكة هولندا'], 'code' => 'NL'),


        );
        foreach ($items as $item) {
            Country::create($item);
        }
        DB::enableQueryLog();
    }
}
