<?php

namespace App\Filament\Resources\PaymentMethodResource\Pages;

use App\Filament\Resources\PaymentMethodResource;
use App\Forms\Components\Translatable;
use App\Forms\Components\TranslatableGrid;
use App\Services\Payment\PaymentService;
use Awcodes\Curator\Components\Forms\CuratorPicker;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Forms\Set;
use Filament\Resources\Pages\CreateRecord;

class CreatePaymentMethod extends CreateRecord
{
    protected static string $resource = PaymentMethodResource::class;

    public function form(Form $form): Form
    {
        return $form->schema(
            [
                Forms\Components\Grid::make(2)->schema([

                    TranslatableGrid::make()->textInput()
                        ->required()
                        ->label(__('wallet.payments.name'))
                        ->required(),
                    Forms\Components\Select::make('type')
                        ->label(__('wallet.payments.type'))
                        ->required()
                        ->reactive()->live()
                        ->selectablePlaceholder(fn($state) => empty($state))
                        ->options(PaymentService::getEnabledPaymentsGetWay())
                        ->afterStateUpdated(function (Set $set, $state) {
                            $set('details', PaymentService::getDefaultData($state));
                            $set('additional_fields', PaymentService::getAdditionalData($state));
                            //$set('name', PaymentService::getDefaultName($state));
                        }),
                    Forms\Components\FileUpload::make('logo')
                        ->label(__('wallet.payments.logo'))
                        ->directory('PaymentLogos')
                        ->acceptedFileTypes(['image/jpeg', 'image/png', 'image/webp']),
                    Forms\Components\KeyValue::make('details')
                        ->label(__('wallet.payments.account_details'))
                        ->editableKeys(false)->addable(false)->deletable(false)->visible(fn($state) => !empty($state)),
                    Forms\Components\KeyValue::make('additional_fields')->label(__('wallet.payments.extra_data'))
                        ->deletable(false)->editableKeys(false)->addable(false)->visible(fn($state) => !empty($state)),
                    Forms\Components\Toggle::make('active')->label(__('string.active'))
                        ->required(),

                ]),






            ]
        ); // TODO: Change the autogenerated stub
    }


}
