<?php

namespace App\Filament\Seller\Resources;

use App\Filament\Seller\Clusters\Settings;
use App\Filament\Seller\Resources\RatingResource\Pages;
use App\Filament\Seller\Resources\RatingResource\RelationManagers;
use App\Models\Rating;
use App\Models\Response;
use App\Models\Seller;
use Filament\Facades\Filament;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\Toggle;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Mokhosh\FilamentRating\Columns\RatingColumn;

class RatingResource extends Resource
{
    protected static ?string $model = Rating::class;

    protected static ?string $navigationIcon = 'heroicon-o-star';
    protected static ?string $cluster = Settings::class;
    public static function canCreate(): bool
    {
        return false;
    }

    protected static bool $shouldSkipAuthorization = true;

    public static function getNavigationLabel(): string
    {
        return __('seller.rate.ratings_and_reviews');
    }

    public static function getModelLabel(): string
    {
        return __('columns.rating'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return  __('seller.rate.ratings_and_reviews');
    }
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                \Mokhosh\FilamentRating\Components\Rating::make('rating')->columnSpanFull()

                    ->label(__('seller.rate.single')),
                Textarea::make('review')->label(__('seller.rate.review'))->columnSpanFull(),

            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                RatingColumn::make('rating')->label(__('seller.rate.single'))->width(150),
                Tables\Columns\TextColumn::make('review')->label(__('seller.rate.review'))->wrap(),
                Tables\Columns\TextColumn::make('created_at')
                    ->width(300)
                    ->label('Created Date')
                    ->label(__('columns.created_at'))
                    ->date(),

            ])
            ->filters([
            ])
            ->actions([
                Tables\Actions\EditAction::make()
                    ->visible(fn($record) => $record->rater_id === Filament::auth()->id() && $record->rater_type === Seller::class),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageRatings::route('/'),
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->joinRelationship('rateable' ,morphable: Response::class)
            ->where(fn($query) => $query
                ->where(fn($query) => $query
                    ->where('rater_id', Filament::auth()->id())
                    ->where('rater_type', Seller::class)
                )
                ->orWhere('responses.seller_id', Filament::auth()->id())
            )->latest();

    }
}
