<?php

namespace App\Filament\Widgets;

use App\Models\Package;
use App\Models\PricingPlan;
use App\Models\Purchase;
use App\Models\Subscription;
use BezhanSalleh\FilamentShield\Traits\HasWidgetShield;
use Filament\Widgets\ChartWidget;
use Filament\Support\RawJs;
use Flowframe\Trend\Trend;
use Flowframe\Trend\TrendValue;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Carbon;
use O21\LaravelWallet\Models\Transaction;

class PurchaseChart extends ChartWidget
{
    use HasWidgetShield;
    protected static ?string $heading = 'Chart';
    protected static ?int $sort = 8;
    protected static bool $isDiscovered = false;
    protected int | string | array $columnSpan = '2';

    protected static ?string $pollingInterval='350s';
    public function getHeading(): string|Htmlable|null
    {
        $currency = getTenant()?->currency?->symbol ?? '';
        return __('wallet.payments.nav_group') . ($currency ? '['. $currency .']' : '');
    }

    public function mount(): void
    {
        $this->filter ??=  date('Y');
        parent::mount(); // TODO: Change the autogenerated stub
    }

    protected function getData(): array
    {
        $activeFilter = $this->filter ?? now()->year;
        $date = $activeFilter ? Carbon::createFromDate($activeFilter, '1', '1') : now();

        $start_date = $date->copy()->startOfYear();
        $end_date = $date->copy()->endOfYear();
        
        // Ensure end_date is properly after start_date
        if ($end_date->lte($start_date)) {
            return $this->getEmptyData();
        }
        
        // For perMonth(), we need at least 2 months difference to ensure CarbonPeriod
        // creates a valid period with at least 1 recurrence
        $monthsDiff = $start_date->copy()->startOfMonth()->diffInMonths($end_date->copy()->startOfMonth(), false);
        
        // If we have less than 2 months, extend the end date
        if ($monthsDiff < 2) {
            $end_date = $start_date->copy()->addMonths(2)->endOfMonth();
        }
        
        // Final validation: ensure end_date is definitely after start_date
        if ($end_date->lte($start_date) || $end_date->equalTo($start_date)) {
            return $this->getEmptyData();
        }
        
        $country_id = filament()->getTenant()?->id ?? getTenant()?->id ?? null;
        
        // In local development, use first country as fallback
        if (!$country_id && app()->environment('local', 'testing', 'staging')) {
            $country_id = \App\Models\Country::first()?->id;
        }
        
        if (!$country_id) {
            // Return empty data if no country/tenant
            return $this->getEmptyData();
        }
        
        $purchases = Purchase:: success($country_id);
        $purchases_subscriptions = Purchase:: success($country_id)->where('purchasable_type', PricingPlan::class);
        $purchases_credit_packages = Purchase:: success($country_id)->where('purchasable_type',  Package::class);
        $purchases_credit_free = Purchase:: success($country_id)->where('purchasable_type', Transaction::class);

        try {
            $data = Trend::query($purchases)->dateColumn('created_at')->between(start: $start_date, end: $end_date)->perMonth()->sum('amount');
            $data_subscriptions = Trend::query($purchases_subscriptions)->dateColumn('created_at')->between(start: $start_date, end: $end_date)->perMonth()->sum('amount');
            $data_packages = Trend::query($purchases_credit_packages)->dateColumn('created_at')->between(start: $start_date, end: $end_date)->perMonth()->sum('amount');
            $data_credit = Trend::query($purchases_credit_free)->dateColumn('created_at')->between(start: $start_date, end: $end_date)->perMonth()->sum('amount');
        } catch (\DateMalformedPeriodStringException | \Exception $e) {
            \Log::warning('PurchaseChart Trend error: ' . $e->getMessage() . ' | Start: ' . $start_date->toDateString() . ' | End: ' . $end_date->toDateString() . ' | Type: ' . get_class($e));
            return $this->getEmptyData();
        }


        return [
            'datasets' => [
                [
                    'label' => __('subscriptions.total_payments'),
                    'data' => $data->map(fn(TrendValue $value) => $value->aggregate),
                    'fill' => 'false',
                    'tension'=> 0.35
                ] ,[
                    'label' => __('subscriptions.subscription_plans'),
                    'data' => $data_subscriptions->map(fn(TrendValue $value) => $value->aggregate),
                    'backgroundColor' => 'green',
                    'borderColor' => 'green',
                    'fill' => 'false',
                    'tension'=> 0.25
                ],
                [
                    'label' => __('wallet.packages.single'),
                    'data' => $data_packages->map(fn(TrendValue $value) => $value->aggregate),
                    'backgroundColor' => 'blue',
                    'borderColor' => 'blue',
                    'fill' => 'false',
                    'tension'=> 0.3
                ],
                [
                    'label' => __('wallet.buy_credit'),
                    'data' => $data_credit->map(fn(TrendValue $value) => $value->aggregate),
                    'backgroundColor' => 'secondary',
                    'borderColor' => 'secondary',
                    'fill' => 'false',
                    'tension'=> 0.23
                ]
            ],
            'labels' => getTranslatedMonths(),
        ];
    }
    protected function getFilters(): ?array
    {
        $years = [];
        for ($year = 2023; $year <= now()->year + 2; $year++) {
            $years[$year] = $year;
        }
        return $years;
    }
    protected function getType(): string
    {
        return 'line';
    }
    protected function getOptions(): RawJs
    {
        $currency = getTenant()?->currency?->symbol ?? "";
        return RawJs::make(<<<JS
        {
            scales: {
                y: {
                    ticks: {
                        callback: (value) => '{$currency}' + value,
                    },
                },
            },
        }
    JS);
    }
    
    protected function getEmptyData(): array
    {
        return [
            'datasets' => [
                [
                    'label' => __('subscriptions.total_payments'),
                    'data' => array_fill(0, 12, 0),
                    'fill' => 'false',
                    'tension'=> 0.35
                ],
                [
                    'label' => __('subscriptions.subscription_plans'),
                    'data' => array_fill(0, 12, 0),
                    'backgroundColor' => 'green',
                    'borderColor' => 'green',
                    'fill' => 'false',
                    'tension'=> 0.25
                ],
                [
                    'label' => __('wallet.packages.single'),
                    'data' => array_fill(0, 12, 0),
                    'backgroundColor' => 'blue',
                    'borderColor' => 'blue',
                    'fill' => 'false',
                    'tension'=> 0.3
                ],
                [
                    'label' => __('wallet.buy_credit'),
                    'data' => array_fill(0, 12, 0),
                    'backgroundColor' => 'secondary',
                    'borderColor' => 'secondary',
                    'fill' => 'false',
                    'tension'=> 0.23
                ]
            ],
            'labels' => getTranslatedMonths(),
        ];
    }

}
