<?php

namespace App\Filament\Widgets;

use App\Models\Subscription;
use BezhanSalleh\FilamentShield\Traits\HasWidgetShield;
use Filament\Widgets\ChartWidget;
use Flowframe\Trend\Trend;
use Flowframe\Trend\TrendValue;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Carbon;

class SubscriptionsChart extends ChartWidget
{
    use HasWidgetShield;
    protected static ?int $sort = 7;
    protected static ?string $pollingInterval = '300s';
    protected static bool $isDiscovered = false;
    protected int | string | array $columnSpan = '2';
    public function getHeading(): string|Htmlable|null
    {
        return __('subscriptions.subscriptions');
    }

    public function mount(): void
    {
        $this->filter ??= date('Y');
        parent::mount(); // TODO: Change the autogenerated stub
    }

    public function getDescription(): ?string
    {
        return __('subscriptions.The number of subscriptions per month for year', ['year' => $this->filter]);
    }

    protected function getFilters(): ?array
    {
        $years = [];
        for ($year = 2023; $year <= now()->year + 2; $year++) {
            $years[$year] = $year;
        }
        return $years;
    }

    protected function getData(): array
    {
        $activeFilter = $this->filter ?? now()->year;
        $date = $activeFilter ? Carbon::createFromDate($activeFilter, '1', '1') : now();

        $start_date = $date->copy()->startOfYear();
        $end_date = $date->copy()->endOfYear();
        
        // Ensure end_date is properly after start_date
        if ($end_date->lte($start_date)) {
            return $this->getEmptyData();
        }
        
        // For perMonth(), we need at least 2 months difference to ensure CarbonPeriod
        // creates a valid period with at least 1 recurrence
        // Calculate the actual months between dates
        $monthsDiff = $start_date->copy()->startOfMonth()->diffInMonths($end_date->copy()->startOfMonth(), false);
        
        // If we have less than 2 months, extend the end date
        // This ensures CarbonPeriod can create a valid period
        if ($monthsDiff < 2) {
            $end_date = $start_date->copy()->addMonths(2)->endOfMonth();
        }
        
        // Final validation: ensure end_date is definitely after start_date
        if ($end_date->lte($start_date) || $end_date->equalTo($start_date)) {
            return $this->getEmptyData();
        }

        $country_id = filament()->getTenant()?->id ?? getTenant()?->id ?? null;
        
        // In local development, use first country as fallback
        if (!$country_id && app()->environment('local', 'testing', 'staging')) {
            $country_id = \App\Models\Country::first()?->id;
        }
        
        if (!$country_id) {
            // Return empty data if no country/tenant
            return $this->getEmptyData();
        }
        
        $subscriptions = Subscription::where('country_id', $country_id);
        
        try {
            $data = Trend::query($subscriptions)
                ->dateColumn('subscribe_at')
                ->between(
                    start: $start_date,
                    end: $end_date,
                )
                ->perMonth()
                ->count();
        } catch (\DateMalformedPeriodStringException | \Exception $e) {
            \Log::warning('SubscriptionsChart Trend error: ' . $e->getMessage() . ' | Start: ' . $start_date->toDateString() . ' | End: ' . $end_date->toDateString() . ' | Type: ' . get_class($e));
            return $this->getEmptyData();
        }

        try {
            $activeData = Trend::query($subscriptions->active())
                ->dateColumn('subscribe_at')
                ->between(
                    start: $start_date,
                    end: $end_date,
                )
                ->perMonth()
                ->count();
        } catch (\DateMalformedPeriodStringException | \Exception $e) {
            \Log::warning('SubscriptionsChart active Trend error: ' . $e->getMessage() . ' | Start: ' . $start_date->toDateString() . ' | End: ' . $end_date->toDateString() . ' | Type: ' . get_class($e));
            return $this->getEmptyData();
        }

        return [
            'datasets' => [
                [
                    'label' => __('labels.all'),
                    'data' => $data->map(fn(TrendValue $value) => $value->aggregate),
                ],
                [
                    'label' => __('subscriptions.status_active'),
                    'data' => $activeData->map(fn(TrendValue $value) => $value->aggregate),
                    'backgroundColor' => 'green',
                    'borderColor' => 'green',
                    'textColor' => 'green',
                ],
            ],
            'labels' => getTranslatedMonths(),
        ];
    }

    protected function getType(): string
    {
        return 'bar';
    }
    
    protected function getEmptyData(): array
    {
        return [
            'datasets' => [
                [
                    'label' => __('labels.all'),
                    'data' => array_fill(0, 12, 0),
                ],
                [
                    'label' => __('subscriptions.status_active'),
                    'data' => array_fill(0, 12, 0),
                    'backgroundColor' => 'green',
                    'borderColor' => 'green',
                    'textColor' => 'green',
                ],
            ],
            'labels' => getTranslatedMonths(),
        ];
    }
}
