<?php

namespace App\Filament\Pages;

use App\Filament\Widgets\CountryPaymentsWidget;
use App\Filament\Widgets\PurchaseChart;
use App\Filament\Widgets\ResponseChart;
use App\Filament\Widgets\Stats;
use App\Filament\Widgets\SubscriptionsChart;
use Filament\Actions\Action;
use Filament\Forms\Components\DatePicker;
use Filament\Pages\Dashboard;
use Filament\Pages\Dashboard\Actions\FilterAction;
use Filament\Pages\Dashboard\Concerns\HasFiltersAction;
use Filament\Widgets\AccountWidget;

class AdminDashboard extends Dashboard
{
    use HasFiltersAction;

    public function getHeaderWidgetsColumns(): int|string|array
    {
        return 2;
    }
    public function getColumns(): int|string|array
    {
        return   4 ;//parent::getColumns(); // TODO: Change the autogenerated stub
    }

    protected function getHeaderWidgets(): array
    {
        return  [
            AccountWidget::class,
        ];
    }

    public function getWidgets(): array
    {
        $country_id = filament()->getTenant()?->id ?? null;
        return [
            Stats::class,
            ResponseChart::class,
            SubscriptionsChart::class,
            PurchaseChart::class,
            CountryPaymentsWidget::class,

        ];
    }

    /*  use HasFiltersForm;

      public function filtersForm(Form $form): Form
      {
          return $form
              ->schema([
                  Section::make()
                      ->schema([
                          DatePicker::make('startDate'),
                          DatePicker::make('endDate'),
                          // ...
                      ])
                      ->columns(3),
              ]);
      }*/
    protected function getHeaderActions(): array
    {
        return [
            FilterAction::make()
                ->extraModalFooterActions([
                    Action::make('reset')
                        ->action(function ($data) {
                            $this->reset($data);
                            $this->closeActionModal();
                        })

                ])
                ->form([
                    DatePicker::make('startDate')->native(),
                    DatePicker::make('endDate')->native(),
                    // ...
                ]),
        ];
    }
}
